FROM alpine:3.24.0

ARG TARGETPLATFORM
COPY $TARGETPLATFORM/mcp-alertmanager /mcp-alertmanager

EXPOSE      8012
ENTRYPOINT  [ "/mcp-alertmanager" ]
CMD         [ "-httpListenAddr=:8012", "-mode=sse" ]
